/**
* PreKara Server API.dev
* PreKaraのバックエンドサーバーのAPIリファレンスです。ライセンス等はリポジトリに準拠します。/apiを叩くとAPIのバージョンが取得できます。
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.prekara.android.Model


/**
 * 
 * @param name
 * @param password 
 */
data class Server (
        val name: String,
        val password: String
) {

    fun toPairList(): List<Pair<String, Any>> {
        return listOf("server_name" to name, "password" to password)
    }

    override fun toString(): String = """
        {
            "server_name": $name,
            "password": $password
        }
        """
}

